[Feature/45] 보틀의 핑퐁 조회하기
Nexters/Bottles_BE pull request #51
Opened 2024-07-24 14:38 UTC by injoon2019

## 💡 이슈 번호
close: #45 

## ✨ 작업 내용
보틀의 핑퐁 조회하기를 구현했습니다

## 🚀 전달 사항
보틀 생성(매칭)시 편지를 넣어줄지 정해야 할거 같아요! 질문리스트는 미리 정해야해서

2024-07-24 15:20 UTC, injoon2019 commented on src/main/kotlin/com/nexters/bottles/user/domain/User.kt
> +    var height: Int,
키가 추가되어서 슬쩍 끼워넣었습니다

2024-07-24 15:36 UTC, miseongk commented
> 보틀 생성(매칭)시 편지를 넣어줄지 정해야 할거 같아요!

이거부터 답변드리면, **보틀 수락할 때** 질문 3개 뽑아서 넣도록 했어요!! 
https://github.com/Nexters/Bottles_BE/pull/28/commits/2ebe2d614f39b4eefb0e45ee1be9ec8148e1e33c 여기 커밋 보시면 3개 뽑아서 Letter 객체 만들어서 저장해요! 답변은 null로 넣고요.

보틀 생성할 때 편지를 넣기에는 거절하는 경우도 많을 것 같아서 불필요한 데이터가 생성되는 것 같아서, 수락할 때 생성되는게 좋다고 생각했어요!

2024-07-24 15:53 UTC, injoon2019 commented
> > 보틀 생성(매칭)시 편지를 넣어줄지 정해야 할거 같아요!
> 
> 이거부터 답변드리면, **보틀 수락할 때** 질문 3개 뽑아서 넣도록 했어요!! [2ebe2d6](https://github.com/Nexters/Bottles_BE/commit/2ebe2d614f39b4eefb0e45ee1be9ec8148e1e33c) 여기 커밋 보시면 3개 뽑아서 Letter 객체 만들어서 저장해요! 답변은 null로 넣고요.
> 
> 보틀 생성할 때 편지를 넣기에는 거절하는 경우도 많을 것 같아서 불필요한 데이터가 생성되는 것 같아서, 수락할 때 생성되는게 좋다고 생각했어요!

오 좋아요!

2024-07-24 16:14 UTC, miseongk requested changes
고생하셨습니다!! 👏
수정할 부분이 살짝 있어서 RC 할게요!

2024-07-24 16:14 UTC, miseongk commented on src/main/kotlin/com/nexters/bottles/bottle/controller/BottleController.kt
> +    @GetMapping("/ping-pong")
여기에 path parameter가 빠졌어요!

2024-07-24 16:14 UTC, miseongk commented on src/main/kotlin/com/nexters/bottles/bottle/facade/BottleFacade.kt
> +        val bottle = bottleService.getBottle(bottleId)
`bottleSevice.getBottle` 이 메서드는 status가 None이고 만료되지 않은 보틀을 가져와서 핑퐁 조회할 때는 적합하지 않아요!
메서드명이 명확하지 않아서 헷갈리긴 하네요 😅

2024-07-24 16:14 UTC, miseongk commented on src/main/kotlin/com/nexters/bottles/bottle/facade/BottleFacade.kt
> +    }
오 이부분 저는 엄청 헷갈리던데 잘하셨네요 👍👍

2024-07-24 16:14 UTC, miseongk commented on src/main/kotlin/com/nexters/bottles/user/domain/User.kt
> +    }
좋아요 👍

2024-07-24 16:14 UTC, miseongk commented on src/main/kotlin/com/nexters/bottles/bottle/service/LetterService.kt
> +    }
보틀 수락할 때 letter가 무조건 생성되니까 return값이 Nullable하지 않아도 될 것 같아요. null이라면 예외처리를 해주는건 어떤가요?

2024-07-24 16:14 UTC, miseongk commented on src/main/kotlin/com/nexters/bottles/bottle/domain/Bottle.kt
> +
엇 사진은 Letter에 있는데 일부러 여기로 옮기신건가요?!

2024-07-24 16:14 UTC, miseongk commented on src/main/kotlin/com/nexters/bottles/bottle/facade/dto/BottlePingPongResponseDto.kt
> +)
API 명세서에 현재 종료된 핑퐁인지에 대한 여부를 반환하는 `isStopped`가 있는데 추가해야 할 것 같아요!
그리고 누구에 의해서 종료됐는지도 화면에 표시가 되어서 그것도 추가해야할 것 같아요.

2024-07-24 16:36 UTC, injoon2019 commented on src/main/kotlin/com/nexters/bottles/bottle/facade/dto/BottlePingPongResponseDto.kt
> +)
넵 이거 추가할게요!

2024-07-24 16:36 UTC, injoon2019 commented on src/main/kotlin/com/nexters/bottles/bottle/domain/Bottle.kt
> +
요거 돌려놓을게요!

2024-07-24 16:36 UTC, injoon2019 commented on src/main/kotlin/com/nexters/bottles/bottle/service/LetterService.kt
> +    }
좋습니다!

2024-07-24 16:57 UTC, injoon2019 commented on src/main/kotlin/com/nexters/bottles/bottle/domain/enum/PingPongStatus.kt
> +    MATCHED, // 매칭이 된 상황
쪼끔 헷갈려서 주석 추가했는데 의도하신게 맞으신지 봐주세요!

2024-07-24 16:57 UTC, injoon2019 commented on src/main/kotlin/com/nexters/bottles/bottle/controller/BottleController.kt
> +        return bottleFacade.getNewBottles()
여긴 정확하게 말하면 NONE인 상태, 즉 받을지 말지 결정 안한애들만 보여주려고 하는거죠?

2024-07-24 16:58 UTC, injoon2019 commented on src/main/kotlin/com/nexters/bottles/bottle/facade/BottleFacade.kt
> +        val bottle = bottleService.getNotExpiredBottle(bottleId, setOf(PingPongStatus.NONE))
여기 헷갈려서 상태를 파라미터로 넘기게 바꿨는데 별로면 다른 의견도 좋아요!

2024-07-24 16:59 UTC, injoon2019 commented
> 고생하셨습니다!! 👏 수정할 부분이 살짝 있어서 RC 할게요!

코드 리뷰 반영했습니다! 아무래도 도메인이 조금씩 복잡해지고 시간관계상 디자인이 모든 영역을 다루지는 못하니 서로 다르게 생각하는 모델이 나올 수 있을거 같아요! 오프라인 때 같이 맞춰봐요!

2024-07-25 04:01 UTC, miseongk commented on src/main/kotlin/com/nexters/bottles/bottle/domain/enum/PingPongStatus.kt
> +    MATCHED, // 매칭이 된 상황
오 맞아요!!

2024-07-25 04:02 UTC, miseongk commented on src/main/kotlin/com/nexters/bottles/bottle/controller/BottleController.kt
> +        return bottleFacade.getNewBottles()
넵 맞아요!

2024-07-25 04:07 UTC, miseongk commented on src/main/kotlin/com/nexters/bottles/bottle/facade/BottleFacade.kt
> +        val bottle = bottleService.getNotExpiredBottle(bottleId, setOf(PingPongStatus.NONE))
오 너무 좋아요! 한번에 이해하기 좋네요 👍

2024-07-25 04:09 UTC, miseongk approved these changes
더 이해하기 좋은 코드로 변경되어서 너무 좋네요 👍
고생하셨습니다!!

2024-07-25 04:09 UTC, miseongk commented on src/main/kotlin/com/nexters/bottles/bottle/facade/BottleFacade.kt
> +            setOf(PingPongStatus.NONE, PingPongStatus.ACTIVE, PingPongStatus.STOPPED, PingPongStatus.MATCHED)
여기서 NONE인 상태는 가져오지 않아도 되지 않나요?
핑퐁을 하게되면 무조건 NONE은 아니기 때문에요!

2024-07-25 04:17 UTC, miseongk commented on src/main/kotlin/com/nexters/bottles/bottle/facade/BottleFacade.kt
> +            setOf(PingPongStatus.NONE, PingPongStatus.ACTIVE, PingPongStatus.STOPPED, PingPongStatus.MATCHED)
엇 근데 생각해보니까 expiredAt은 보틀 매칭되고 24시간 이후로 설정되어서 핑퐁 조회할 때는 expiredAt을 조건에 넣으면 안될 것 같아요!

2024-07-25 13:05 UTC, merged